"""Dashboard wrappers for follow vision account files."""

from __future__ import annotations

from typing import Any

from dashboard.gramaddict_config import ACCOUNTS_DIR, _save_yaml
from GramAddict.core import follow_vision_account as fva

FOLLOW_VISION_FIELDS: list[dict[str, Any]] = [
    {
        "key": "enabled",
        "label": "Enable follow vision filter",
        "type": "bool",
        "default": False,
    },
    {
        "key": "prompt-batch",
        "label": "Vision prompt batch",
        "type": "select",
        "options": ["615FILMS", "YourLoveFilms"],
        "default": "615FILMS",
    },
    {
        "key": "log-videographers",
        "label": "Save vendors & add to blogger-followers live",
        "type": "bool",
        "default": True,
    },
    {
        "key": "ai-comment-enabled",
        "label": "AI-generated comments",
        "type": "bool",
        "default": False,
    },
    {
        "key": "ai-comment-prompt",
        "label": "AI comment prompt",
        "type": "textarea",
        "default": fva.DEFAULT_COMMENT_PROMPT,
    },
    {
        "key": "ai-pm-enabled",
        "label": "AI-generated DMs",
        "type": "bool",
        "default": False,
    },
    {
        "key": "pm-private-only",
        "label": "Skip DMing public accounts",
        "type": "bool",
        "default": False,
    },
    {
        "key": "ai-pm-prompt",
        "label": "AI DM prompt",
        "type": "textarea",
        "default": fva.DEFAULT_PM_PROMPT,
    },
    {
        "key": "vision-popup-dismiss",
        "label": "Auto-dismiss popups with vision",
        "type": "bool",
        "default": True,
    },
]

FOLLOW_VISION_HELP: dict[str, str] = {
    "enabled": (
        "Before interacting with a profile, screenshot it and ask OpenAI Vision "
        "whether it matches your prompt. Profiles that fail are skipped."
    ),
    "prompt-batch": "Which vision prompt to use — 615FILMS (musicians) or YourLoveFilms (couples, not vendors).",
    "log-videographers": (
        "Works for both accounts — Tennessee only. 615FILMS: when vision finds a "
        "TN music videographer (bio/location in Tennessee / TN cities / abbreviations), "
        "saves them to found_videographers_tn.txt and adds them to blogger-followers "
        "live. YourLoveFilms: when vision finds a TN wedding photographer/videographer, "
        "saves them to found_wedding_vendors.txt (and wedding_videographers.txt) and "
        "adds them to blogger-followers live so the bot can use them in the same session. "
        "Non-TN vendors are ignored."
    ),
    "ai-comment-enabled": (
        "When enabled, comments are generated by OpenAI using the prompt below — "
        "not from Comments & PM → comments_list.txt."
    ),
    "ai-comment-prompt": (
        "Instructions for the AI comment, e.g. a short casual 'let's work soon' message. "
        "Uses the follow_vision.yml / post_reel.yml API key."
    ),
    "ai-pm-enabled": (
        "When enabled, DMs are generated by OpenAI using the prompt below — "
        "not from Comments & PM → pm_list.txt (that file is still used as fallback)."
    ),
    "pm-private-only": (
        "If a profile is public, the bot still visits it but will not send a DM. "
        "Only private accounts get messaged. Does not skip the whole profile."
    ),
    "ai-pm-prompt": (
        "Instructions for the AI DM, e.g. a congrats-on-your-big-day message from a mutual. "
        "Uses the follow_vision.yml / post_reel.yml API key."
    ),
    "vision-popup-dismiss": (
        "When a tap/selector can't find its target, a popup or permission sheet is "
        "often covering the screen. If enabled, the bot screenshots the screen, asks "
        "OpenAI Vision where the dismiss button is, and taps it so the session can "
        "recover. Uses the follow_vision.yml / post_reel.yml API key."
    ),
}


def get_follow_vision_schema() -> dict[str, Any]:
    from dashboard.gramaddict_field_help import enrich_fields

    return {"fields": enrich_fields(FOLLOW_VISION_FIELDS, FOLLOW_VISION_HELP)}


def get_account_follow_vision(account_id: str) -> dict[str, Any]:
    data = fva.get_account_follow_vision(account_id)
    # Runtime flag lives in filters.yml; surface it next to the AI DM controls.
    filters_path = ACCOUNTS_DIR / account_id / "filters.yml"
    filters = _load_filters(filters_path)
    data["pm-private-only"] = bool(filters.get("pm_private_only", False))
    return data


def _load_filters(path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        import yaml

        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _sync_pm_private_only(account_id: str, enabled: bool) -> None:
    """Write pm_private_only into filters.yml (bot reads it at runtime)."""
    path = ACCOUNTS_DIR / account_id / "filters.yml"
    data = _load_filters(path)
    data["pm_private_only"] = bool(enabled)
    if enabled:
        # Private DMs require the allow-private flag as well.
        data["pm_to_private_or_empty"] = True
    _save_yaml(path, data)


def save_account_follow_vision(account_id: str, updates: dict[str, Any]) -> dict[str, Any]:
    path = ACCOUNTS_DIR / account_id / fva.FOLLOW_VISION_FILENAME
    data = fva.get_account_follow_vision(account_id)
    sync_private_only = "pm-private-only" in updates
    private_only_value = bool(updates.get("pm-private-only", False)) if sync_private_only else None

    for key, value in updates.items():
        if key == "pm-private-only":
            # Stored in filters.yml, not follow_vision.yml.
            continue
        if key in {
            "enabled",
            "log-videographers",
            "log-tn-videographers",
            "ai-comment-enabled",
            "ai-pm-enabled",
            "vision-popup-dismiss",
        }:
            data[key] = bool(value)
            if key == "log-videographers":
                data["log-tn-videographers"] = bool(value)
        else:
            data[key] = value
    data.pop("openai-model", None)
    data.pop("pm-private-only", None)
    data.pop("pm_private_only", None)
    _save_yaml(path, data)

    if sync_private_only and private_only_value is not None:
        _sync_pm_private_only(account_id, private_only_value)

    return get_account_follow_vision(account_id)


def get_account_follow_vision_prompts(account_id: str) -> dict[str, str]:
    return fva.get_account_follow_vision_prompts(account_id)


def save_account_follow_vision_prompts(
    account_id: str, updates: dict[str, str]
) -> dict[str, str]:
    path = ACCOUNTS_DIR / account_id / fva.FOLLOW_VISION_PROMPTS_FILENAME
    data = get_account_follow_vision_prompts(account_id)
    data.update({k: str(v) for k, v in updates.items()})
    _save_yaml(path, data)
    return get_account_follow_vision_prompts(account_id)
