"""Dashboard wrappers for follow vision account files."""

from __future__ import annotations

from typing import Any

from dashboard.gramaddict_config import ACCOUNTS_DIR, _save_yaml
from GramAddict.core import follow_vision_account as fva

FOLLOW_VISION_FIELDS: list[dict[str, Any]] = [
    {
        "key": "enabled",
        "label": "Enable follow vision filter",
        "type": "bool",
        "default": False,
    },
    {
        "key": "prompt-batch",
        "label": "Vision prompt batch",
        "type": "select",
        "options": ["615FILMS", "YourLoveFilms"],
        "default": "615FILMS",
    },
    {
        "key": "log-videographers",
        "label": "Save vendors & add to blogger-followers live",
        "type": "bool",
        "default": True,
    },
    {
        "key": "ai-comment-enabled",
        "label": "AI-generated comments",
        "type": "bool",
        "default": False,
    },
    {
        "key": "ai-comment-prompt",
        "label": "AI comment prompt",
        "type": "textarea",
        "default": fva.DEFAULT_COMMENT_PROMPT,
    },
    {
        "key": "vision-popup-dismiss",
        "label": "Auto-dismiss popups with vision",
        "type": "bool",
        "default": True,
    },
]

FOLLOW_VISION_HELP: dict[str, str] = {
    "enabled": (
        "Before interacting with a profile, screenshot it and ask OpenAI Vision "
        "whether it matches your prompt. Profiles that fail are skipped."
    ),
    "prompt-batch": "Which vision prompt to use — 615FILMS (musicians) or YourLoveFilms (couples, not vendors).",
    "log-videographers": (
        "Works for both accounts — Tennessee only. 615FILMS: when vision finds a "
        "TN music videographer (bio/location in Tennessee / TN cities / abbreviations), "
        "saves them to found_videographers_tn.txt and adds them to blogger-followers "
        "live. YourLoveFilms: when vision finds a TN wedding photographer/videographer, "
        "saves them to found_wedding_vendors.txt (and wedding_videographers.txt) and "
        "adds them to blogger-followers live so the bot can use them in the same session. "
        "Non-TN vendors are ignored."
    ),
    "ai-comment-enabled": (
        "When enabled, comments are generated by OpenAI using the prompt below — "
        "not from Comments & PM → comments_list.txt."
    ),
    "ai-comment-prompt": (
        "Instructions for the AI comment, e.g. a short casual 'let's work soon' message. "
        "Uses the follow_vision.yml / post_reel.yml API key."
    ),
    "vision-popup-dismiss": (
        "When a tap/selector can't find its target, a popup or permission sheet is "
        "often covering the screen. If enabled, the bot screenshots the screen, asks "
        "OpenAI Vision where the dismiss button is, and taps it so the session can "
        "recover. Uses the follow_vision.yml / post_reel.yml API key."
    ),
}


def get_follow_vision_schema() -> dict[str, Any]:
    from dashboard.gramaddict_field_help import enrich_fields

    return {"fields": enrich_fields(FOLLOW_VISION_FIELDS, FOLLOW_VISION_HELP)}


def get_account_follow_vision(account_id: str) -> dict[str, Any]:
    return fva.get_account_follow_vision(account_id)


def save_account_follow_vision(account_id: str, updates: dict[str, Any]) -> dict[str, Any]:
    path = ACCOUNTS_DIR / account_id / fva.FOLLOW_VISION_FILENAME
    data = get_account_follow_vision(account_id)
    for key, value in updates.items():
        if key in {"enabled", "log-videographers", "log-tn-videographers", "ai-comment-enabled", "vision-popup-dismiss"}:
            data[key] = bool(value)
            if key == "log-videographers":
                data["log-tn-videographers"] = bool(value)
        else:
            data[key] = value
    data.pop("openai-model", None)
    _save_yaml(path, data)
    return get_account_follow_vision(account_id)


def get_account_follow_vision_prompts(account_id: str) -> dict[str, str]:
    return fva.get_account_follow_vision_prompts(account_id)


def save_account_follow_vision_prompts(
    account_id: str, updates: dict[str, str]
) -> dict[str, str]:
    path = ACCOUNTS_DIR / account_id / fva.FOLLOW_VISION_PROMPTS_FILENAME
    data = get_account_follow_vision_prompts(account_id)
    data.update({k: str(v) for k, v in updates.items()})
    _save_yaml(path, data)
    return get_account_follow_vision_prompts(account_id)
