username: laurenpk.222
app-id: com.instagram.android
use-cloned-app: false
allow-untested-ig-version: true
ensure-vpn: false
vpn-app-name: Shadowrocket
screen-sleep: true
screen-record: false
speed-multiplier: '1'
debug: false
close-apps: false
kill-atx-agent: false
restart-atx-agent: false
disable-block-detection: false
disable-filters: false
dont-type: false
total-crashes-limit: '5'
count-app-crashes: false
shuffle-jobs: false
truncate-sources: 2-5
post-reels: '0'
blogger-post-likers:
- d2m_____
- swuegopersona
- fourfourfour___
- mezcalpapi
- officialyoungmark
- cg_montana_
- dxn.rxn
- officialmrzika
- '*pablomcm*'
- aondolla
- osm.mel
- spaindagoat
- ikeepit_105
- capocapone_gse
- PesoTaxin
- 4th_quarter_niya
- baybdt
- bigmurph
- frenchie_mcm
- troybandz
- youngprofessa
- xtgetlow
- jjcontreras
- goodmorningcoffee
- legendary-champ
- illcapo (manager)
- zoticdagod
- the4kj
- kingsharcon (manager)
- sideshowgamo
- mr.lost
- chrisstylespoppin
- sk_tgm
- b_king101
- kingzayy__
- luhherm
- squidmakesmusic
- tdotmase
- 3stonespliff
- kleomcm
- billyjumpmane
- officialyflex
- iambversa
- baybay2hbk
- tdavisssss1
- coca_iam
- yungcoca
- K-Ozz
- spodie_ro
- jayedolla
- treymcclainmusic
- hatesoze
- smokeymanebaby
- iamandredevonte
- t.b.e_5l_mal
- lostkingjrich
- liljbone83
- its_t_rich
- kee_money1
- chieff_2hunna
- fritzappeal
- emancloudboysanchez
- your_favorite_artist_2j
- '*janitas*'
- iamyungjayy__
- '**dtjl'
- youngdrip615
- kvproductions901
- famerica_kemistry
- srt_quazzy*
- xcplee/ ayecplee
- ipissgreatness
- ogf.n24
- mr_sellyasumn
- hitmakaeazy
- ynbbreezyoffical
- gemini_moon_goddess5
- nashvillianfoodie
- smokeymanebaby
- ebenelite
- vivalamegz
- thisissiege
- shelovesflacko
- cbandz615
- cartermusicent
- realjuizelee
- clothwyzard*
- goosesavetheworld
- bossman_dfo
- '*supermareio'
- djfrm33rd
- deathakiddd
- tharealfrankd
- moneymarco615
- bigzayee
- rashunfuture
- targetboidraco
- lyricalsheart
- '*thereal.toot/'
- sumlin21
- moneymarco615/traplyfepablo615
- r3allye
- newjackbaby_20
- t.r.e.6
- bekuhboom
- d3carso
- spodie_ro
- jayedolla
- treymcclainmusic
- hatesoze
- smokeymanebaby
- iamandredevonte
- t.b.e_5l_mal
- lostkingjrich
- liljbone83
- its_t_rich
- kee_money1
- chieff_2hunna
- fritzappeal
- emancloudboysanchez
- your_favorite_artist_2j
- '*janitas*'
- iamyungjayy**
- '**dtjl'
- youngdrip615
- kvproductions901
- famerica_kemistry
- srt_quazzy*
- xcplee/ ayecplee
- ipissgreatness
- ogf.n24
- mr_sellyasumn
- hitmakaeazy
- gemini_moon_goddess5
- colion608/
- smokeymanebaby
- ebenelite
- vivalamegz
- thisissiege
- shelovesflacko
- cbandz615
- cartermusicent
- realjuizelee
- ynbbreezyoffical
- nashvillianfoodie
- clothwyzard*
- goosesavetheworld
- bossman_dfo
- _supermareio
- djfrm33rd
- deathakiddd
- tharealfrankd
- moneymarco615
- bigzayee
- rashunfuture
- targetboidraco
- lyricalsheart
- _thereal.toot
- sumlin21
- moneymarco615/traplyfepablo615
- r3allye
- newjackbaby_20
- t.r.e.6
- bekuhboom
- d3carso
- officialcashkruger
- loganbolton
- thefatherearth
- mianalaide
- therealls4
- mrmrking
- gmt_mobdee
- youngnesian
- darealtuk
- drosefasho
- zayfvckinlyve
- princ3.maj
- whoisdon
- shelovesflacko
- __streetstar
- trontheking
- bandoboss74
- newjack.dre
place-posts-top:
- place1
- place2
place-posts-recent:
- place1
- place2
place-likers-top:
- place1
- place2
place-likers-recent:
- place1
- place2
feed: 1-2
watch-video-time: 5-35
watch-photo-time: 1-3
delete-interacted-users: true
unfollow: 10-20
unfollow-any: 10-20
unfollow-non-followers: 10-20
unfollow-any-non-followers: 10-20
unfollow-any-followers: 10-20
unfollow-from-file:
- unfollow_list.txt 1-2
sort-followers-newest-to-oldest: false
unfollow-delay: '15'
remove-followers-from-file:
- remove_list.txt 1-2
delete-removed-followers: true
telegram-reports: true
interactions-count: 30-40
likes-count: 1-2
likes-percentage: '100'
stories-count: 1-2
stories-percentage: 30-40
carousel-count: 1-3
carousel-percentage: 60-70
follow-percentage: '100'
follow-limit: '50'
skipped-list-limit: 10-15
skipped-posts-limit: '5'
fling-when-skipped: '0'
min-following: '100'
total-likes-limit: 80-120
total-follows-limit: 40-50
total-unfollows-limit: 40-50
total-watches-limit: 120-150
total-successful-interactions-limit: 120-150
total-interactions-limit: 280-300
total-comments-limit: 3-5
total-pm-limit: '0'
total-scraped-limit: 100-150
end-if-likes-limit-reached: false
end-if-follows-limit-reached: true
end-if-watches-limit-reached: false
end-if-comments-limit-reached: false
end-if-pm-limit-reached: false
working-hours:
- 21.30-0.00
- 18.15-22.46
time-delta: '1'
total-sessions: '1'
repeat: 280-320
unfollow-from-list: 1-2
remove-followers-from-list: 1-2
max-comments-pro-user: '1'
comment-percentage: '100'
interact-percentage: '0'
