name: YLF Updated Main
source_account: yourlovefilms
created_at: '2026-07-13T21:31:51Z'
files: [config.yml, filters.yml, telegram.yml, post_reel.yml, post_reel_prompts.yml, follow_vision.yml, follow_vision_prompts.yml, comments_list.txt, pm_list.txt, story_likes.meta.yml, whitelist.txt, blacklist.txt, story_likes.txt, unfollow_list.txt, remove_list.txt]
updated_at: '2026-07-15T23:03:07Z'
